### ISSUE TITLE
Docker Hub のイメージにタグをつけてほしい

### ISSUE THREAD

**Issue by inutano** [dbcls/sparql-proxy#18]
Dockerコンテナが用意してあるので楽にお試しできて最高なのですが、ビルドされたイメージが latest しか用意されておらずプロダクションに使えません… リリースバージョンに倣ったコンテナのタグをつけてほしいです！
https://hub.docker.com/r/dbcls/sparql-proxy/tags

**Comment by ktym** [comment]
https://github.com/dbcls/sparqlist/issues/15#issuecomment-632570047 同様に対応済み
