### ISSUE TITLE
Build instructions fail

### ISSUE THREAD

**Issue by kidehen** [dbcls/sparql-proxy#2]
Following you build instructions I end up with the following (note: I am using Mac OS X): 

1794 error Darwin 15.6.0
1795 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "snappy@4.1.2"
1796 error node v6.11.3
1797 error npm  v3.10.10
1798 error code ELIFECYCLE
1799 error snappy@4.1.2 install: `node-gyp rebuild`
1799 error Exit status 1
1800 error Failed at the snappy@4.1.2 install script 'node-gyp rebuild'.
1800 error Make sure you have the latest version of node.js and npm installed.
1800 error If you do, this is most likely a problem with the snappy package,
1800 error not with npm itself.
1800 error Tell the author that this fails on your system:
1800 error     node-gyp rebuild
1800 error You can get information on how to open an issue for this project with:
1800 error     npm bugs snappy
1800 error Or if that isn't available, you can get their info via:
1800 error     npm owner ls snappy
1800 error There is likely additional logging output above.
1801 verbose exit [ 1, true ]

Also note output of **node -v:** 
v6.11.3

**Comment by ktym** [comment]
Couldn't be reproduced with a recent environment (try Node.js v8 or later).
